packages:
  - apps/*
  - packages/*

allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true
  mongodb-memory-server: true
  '@firebase/util': true
  protobufjs: true
  esbuild@0.27.0: true

minimumReleaseAgeExclude:
  - zod@4.6.4

overrides:
  "jwks-rsa>jose": "4.15.9"
