"use client";
import {useState} from "react";import Link from "next/link";import {useRouter} from "next/navigation";import {Eye,EyeOff,GraduationCap,LoaderCircle,School,ShieldCheck} from "lucide-react";import {loginSchema,registerSchema} from "@eduflux/validation";import type {AuthSession,PrimaryPersona} from "@eduflux/shared-types";import {firebaseErrorMessage,loginWithEmail,loginWithGoogle,registerWithEmail} from "@/lib/firebase/auth";

export function AuthForm({mode}:{mode:"login"|"register"}){
 const router=useRouter();const[persona,setPersona]=useState<PrimaryPersona>("TEACHER");const[showPassword,setShowPassword]=useState(false);const[pending,setPending]=useState(false);const[error,setError]=useState("");const[fields,setFields]=useState<Record<string,string[]>>({});
 function redirect(session:AuthSession){router.replace(session.requiresOnboarding?"/onboarding":session.user.primaryPersona==="TEACHER"?"/teacher/dashboard":"/student/dashboard");router.refresh()}
 async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(pending)return;setError("");setFields({});const form=new FormData(event.currentTarget);const input=mode==="register"?{displayName:String(form.get("displayName")??""),email:String(form.get("email")??""),password:String(form.get("password")??""),primaryPersona:persona}:{email:String(form.get("email")??""),password:String(form.get("password")??"")};const parsed=(mode==="register"?registerSchema:loginSchema).safeParse(input);if(!parsed.success){setFields(parsed.error.flatten().fieldErrors);setError("Please check the highlighted fields.");return}setPending(true);try{const session=mode==="register"?await registerWithEmail(parsed.data as typeof input&{displayName:string;primaryPersona:PrimaryPersona}):await loginWithEmail((parsed.data as {email:string;password:string}).email,(parsed.data as {email:string;password:string}).password);redirect(session)}catch(caught){setError(firebaseErrorMessage(caught))}finally{setPending(false)}}
 async function google(){if(pending)return;setPending(true);setError("");try{redirect(await loginWithGoogle())}catch(caught){setError(firebaseErrorMessage(caught))}finally{setPending(false)}}
 return <div className="auth-card"><div className="auth-card-heading"><span><ShieldCheck aria-hidden="true"/></span><div><h2>{mode==="register"?"Create your account":"Welcome back"}</h2><p>{mode==="register"?"Choose your starting workspace.":"Sign in to continue to your classes."}</p></div></div><button className="google-auth-button" type="button" onClick={google} disabled={pending} aria-label="Continue with Google"><GoogleMark/>Continue with Google</button><div className="auth-divider"><span>or continue with email</span></div><form onSubmit={submit} noValidate>{error&&<div className="form-error" role="alert">{error}</div>}{mode==="register"&&<><fieldset className="persona-field"><legend>I’m joining as a</legend><div>{(["TEACHER","STUDENT"]as const).map(value=><button key={value} type="button" aria-pressed={persona===value} onClick={()=>setPersona(value)}>{value==="TEACHER"?<School aria-hidden="true"/>:<GraduationCap aria-hidden="true"/>}<span>{value==="TEACHER"?"Teacher":"Student"}<small>{value==="TEACHER"?"Create and guide classes":"Join and learn with a class"}</small></span></button>)}</div></fieldset><Field label="Display name" name="displayName" autoComplete="name" error={fields.displayName?.[0]}/></>}<Field label="Email address" name="email" type="email" autoComplete="email" error={fields.email?.[0]}/><div className="password-field"><Field label="Password" name="password" type={showPassword?"text":"password"} autoComplete={mode==="register"?"new-password":"current-password"} description={mode==="register"?"Use at least 12 characters.":undefined} error={fields.password?.[0]}/><button className="password-toggle" type="button" onClick={()=>setShowPassword(value=>!value)} aria-label={showPassword?"Hide password":"Show password"}>{showPassword?<EyeOff aria-hidden="true"/>:<Eye aria-hidden="true"/>}</button></div><button className="button button-primary auth-submit" disabled={pending}>{pending&&<LoaderCircle className="spinner" aria-hidden="true"/>}{pending?"Please wait…":mode==="register"?"Create account":"Sign in"}</button></form><p className="auth-switch">{mode==="register"?"Already have an account?":"New to EduFlux?"} <Link href={mode==="register"?"/login":"/register"}>{mode==="register"?"Sign in":"Create account"}</Link></p></div>
}
function GoogleMark(){return <svg viewBox="0 0 24 24" aria-hidden="true"><path fill="#4285F4" d="M21.6 12.2c0-.7-.1-1.4-.2-2H12v3.9h5.4a4.6 4.6 0 01-2 3v2.5h3.2c1.9-1.7 3-4.3 3-7.4"/><path fill="#34A853" d="M12 22c2.7 0 5-.9 6.6-2.4l-3.2-2.5c-.9.6-2 1-3.4 1-2.6 0-4.8-1.8-5.6-4.2H3.1v2.6A10 10 0 0012 22"/><path fill="#FBBC05" d="M6.4 13.9A6 6 0 016.1 12c0-.7.1-1.3.3-1.9V7.5H3.1A10 10 0 002 12c0 1.6.4 3.1 1.1 4.5z"/><path fill="#EA4335" d="M12 5.9c1.5 0 2.8.5 3.8 1.5l2.9-2.8A9.7 9.7 0 0012 2a10 10 0 00-8.9 5.5l3.3 2.6c.8-2.4 3-4.2 5.6-4.2"/></svg>}
function Field({label,name,type="text",autoComplete,description,error}:{label:string;name:string;type?:string;autoComplete:string;description?:string|undefined;error?:string|undefined}){const describedBy=error?`${name}-error`:description?`${name}-description`:undefined;return <label className="form-field"><span>{label}</span><input name={name} type={type} autoComplete={autoComplete} aria-invalid={Boolean(error)} aria-describedby={describedBy}/>{description&&!error&&<small id={`${name}-description`}>{description}</small>}{error&&<small className="field-error" id={`${name}-error`}>{error}</small>}</label>}
