"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { ArrowRight, BookOpen, Copy, LoaderCircle, Plus, Users } from "lucide-react";
import type { ClassSummary } from "@eduflux/shared-types";
import { classesApi } from "@/lib/api/classes";
import { ApiClientError } from "@/lib/api/client";

export function ClassDashboard({ mode }: { mode: "teacher" | "student" }) {
  const [classes, setClasses] = useState<ClassSummary[]>([]);
  const [loading, setLoading] = useState(true);
  const [pending, setPending] = useState(false);
  const [error, setError] = useState("");
  useEffect(() => { let active = true; classesApi.mine().then((result) => { if (active) setClasses(result.classes); }).catch(() => { if (active) setError("Classes could not be loaded."); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, []);
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); if (pending) return; setPending(true); setError(""); const form = new FormData(event.currentTarget); try { const description = String(form.get("description") ?? ""); const item = mode === "teacher" ? await classesApi.create({ name: String(form.get("name") ?? ""), ...(description ? { description } : {}) }) : await classesApi.join(String(form.get("joinCode") ?? "")); setClasses((current) => [item, ...current]); event.currentTarget.reset(); } catch (caught) { setError(caught instanceof ApiClientError ? caught.message : "The request could not be completed."); } finally { setPending(false); } }
  return <main className="dashboard"><header className="dashboard-heading"><div><p className="eyebrow">Your learning spaces</p><h1>{mode === "teacher" ? "Classes you guide" : "Classes you’re learning in"}</h1><p>{mode === "teacher" ? "Create a focused home for your next group." : "Use the code from your teacher to join a class."}</p></div></header><section className="class-action" aria-labelledby="class-action-title"><div><span>{mode === "teacher" ? <Plus aria-hidden="true" /> : <BookOpen aria-hidden="true" />}</span><div><h2 id="class-action-title">{mode === "teacher" ? "Create a class" : "Join a class"}</h2><p>{mode === "teacher" ? "You’ll receive a secure code to share." : "Class codes contain eight characters."}</p></div></div><form onSubmit={submit}>{mode === "teacher" ? <><label><span>Class name</span><input name="name" minLength={2} maxLength={100} required placeholder="e.g. Year 10 Literature" /></label><label><span>Description <small>optional</small></span><input name="description" maxLength={500} placeholder="A short note about this class" /></label></> : <label><span>Class code</span><input className="code-input" name="joinCode" minLength={8} maxLength={8} required autoCapitalize="characters" placeholder="ABCD2345" /></label>}<button className="button button-primary" disabled={pending}>{pending && <LoaderCircle className="spinner" />}{pending ? (mode === "teacher" ? "Creating class…" : "Joining class…") : (mode === "teacher" ? "Create class" : "Join class")}</button></form>{error && <p className="form-error" role="alert">{error}</p>}</section><section className="class-list" aria-live="polite">{loading ? <div className="class-skeletons" aria-label="Loading classes"><i /><i /><i /></div> : classes.length === 0 ? <div className="empty-state"><BookOpen aria-hidden="true" /><h2>No classes yet</h2><p>{mode === "teacher" ? "Create your first class above." : "Enter a class code above when you’re ready."}</p></div> : <div className="class-grid">{classes.map((item) => <article className="class-card" key={item.id}><div className="class-card-top"><span>{item.name.slice(0,2).toUpperCase()}</span><small>{item.role}</small></div><h2>{item.name}</h2>{item.description && <p>{item.description}</p>}<div className="class-meta">{item.memberCount !== undefined && <span><Users aria-hidden="true" />{item.memberCount} members</span>}<span>Joined {new Date(item.joinedAt).toLocaleDateString()}</span></div>{item.joinCode && <button type="button" className="join-code" onClick={() => navigator.clipboard.writeText(item.joinCode!)} aria-label={`Copy join code ${item.joinCode}`}>{item.joinCode}<Copy aria-hidden="true" /></button>}<Link href={`/${mode}/classes/${item.id}`}>Open class <ArrowRight aria-hidden="true" /></Link></article>)}</div>}</section></main>;
}
