"use client";
/* eslint-disable @next/next/no-img-element -- private signed R2 URLs intentionally bypass image optimization */
import { useEffect, useMemo, useState, type ReactNode } from "react";
import type { SubmissionReviewDto } from "@eduflux/shared-types";
import { FileImage, FileText, X } from "lucide-react";
import { notify } from "@/lib/notifications";

type Issue = SubmissionReviewDto["issues"][number];

export function SubmissionReview({ review, onSaveComment }: { review: SubmissionReviewDto; onSaveComment?: (comment: string) => Promise<SubmissionReviewDto> }) {
  const [mode, setMode] = useState<"file" | "text">(review.transcribedText || review.typedText ? "text" : "file");
  const [fileIndex, setFileIndex] = useState(0), [pageNumber, setPageNumber] = useState(1);
  const [comment, setComment] = useState(review.teacherComment ?? ""), [saving, setSaving] = useState(false);
  const [selectedIssueId, setSelectedIssueId] = useState<string | null>(null);
  const selectedIssue = useMemo(() => review.issues.find((issue) => issue.id === selectedIssueId), [review.issues, selectedIssueId]);
  const issueGroups = useMemo(() => groupIssues(review.issues), [review.issues]);
  useEffect(() => { const close = (event: KeyboardEvent) => { if (event.key === "Escape") setSelectedIssueId(null); }; window.addEventListener("keydown", close); return () => window.removeEventListener("keydown", close); }, []);

  if (review.status === "PENDING" || review.status === "PROCESSING") return <section className="review-status workspace-card" aria-live="polite"><span className="review-spinner" aria-hidden="true"/><h1>{review.statusMessage ?? (review.status === "PENDING" ? "Preparing your review..." : "Analyzing your submission...")}</h1><p>Your submitted work is safely stored. This page will update automatically.</p></section>;
  if (review.status === "FAILED") return <section className="review-status workspace-card" aria-live="polite"><h1>We couldn&apos;t complete the automated review.</h1><p>{review.statusMessage ?? "Your submission is still safely stored."}</p>{review.typedText && <div className="review-text"><h2>Submitted text</h2><p>{review.typedText}</p></div>}{review.files.length > 0 && <div><h2>Submitted files</h2>{review.files.map((file) => <a key={file.id} href={file.contentUrl} target="_blank" rel="noreferrer">{file.originalName}</a>)}</div>}</section>;

  const file = review.files[fileIndex];
  const pages = review.ocrPages?.filter((page) => page.sourceFileId === file?.id) ?? [];
  return <div className="submission-review">
    <header className="review-identity"><div><p className="eyebrow">Submission review · Attempt {review.attemptNumber}</p><h1>{review.student.displayName}</h1><p>Submitted {new Date(review.submittedAt).toLocaleString()} · Rubric revision {review.rubricRevisionNumber ?? "—"}</p></div></header>
    <section className="review-shell">
      <aside className="review-sidebar">
        <section className="review-side-card"><div className="review-side-heading"><h2>Overall Score</h2><strong>{review.overallScore ?? "—"} / {review.maxScore ?? "—"}</strong></div><ScoreRing score={review.overallScore} max={review.maxScore}/></section>
        <section className="review-side-card"><h2>Correction Statistics</h2><div className="review-stat-list">{Object.entries(review.correctionStats).map(([label, count]) => <div key={label}><span><b>{formatLabel(label)}</b><strong>{count}</strong></span><i style={{ width: `${Math.min(100, count * 8)}%` }}/></div>)}</div></section>
        <section className="review-side-card"><h2>Correction Legend</h2><ul className="legend-list">{review.legendSummary.map((item) => <li key={item.code}><code>{item.code}</code><span>{item.label}</span><strong>{item.count}</strong></li>)}</ul></section>
      </aside>
      <main className="review-main">
        <section className="workspace-card review-document-card"><header className="review-document-header"><div><p className="eyebrow">Student work</p><h2>{mode === "text" ? "Student’s Transcribed Text" : "Student’s Uploaded File"}</h2></div><div className="review-view-switch" role="tablist" aria-label="Review view"><button role="tab" aria-selected={mode === "text"} onClick={() => setMode("text")}><FileText/>View Transcribed Text</button><button role="tab" aria-selected={mode === "file"} disabled={!file} onClick={() => setMode("file")}><FileImage/>View Uploaded Work</button></div></header>
          {mode === "file" && file ? <ReviewFile review={review} file={file} files={review.files} fileIndex={fileIndex} setFileIndex={setFileIndex} pages={pages} pageNumber={pageNumber} setPageNumber={setPageNumber} selectedIssueId={selectedIssueId} onSelectIssue={setSelectedIssueId}/> : <ReviewText review={review} onSelectIssue={setSelectedIssueId}/>} 
          {selectedIssue && <IssuePopover issue={selectedIssue} onClose={() => setSelectedIssueId(null)}/>} 
        </section>
        <section className="review-section"><header><p className="eyebrow">Actionable review</p><h2>Detailed Feedback &amp; Suggestions</h2></header><div className="review-feedback-grid">{[...issueGroups].map(([category, issues]) => <article key={category}><header><h3>{formatLabel(category)}</h3><span>{issues.length} {issues.length === 1 ? "issue" : "issues"}</span></header>{issues.slice(0, 4).map((issue) => <button key={issue.id} onClick={() => setSelectedIssueId(issue.id)}><code>{issue.code}</code><span><del>{issue.originalText}</del>{issue.suggestedText && <ins>{issue.suggestedText}</ins>}</span></button>)}</article>)}</div></section>
        <section className="review-section"><header><p className="eyebrow">What worked well</p><h2>Evidence-based Strengths</h2></header><div className="strength-grid">{review.strengths.map((strength) => <article key={strength.title}><h3>{formatLabel(strength.title)}</h3><p>{strength.description}</p></article>)}</div></section>
        <section className="review-section"><header><p className="eyebrow">Rubric scoring</p><h2>AI-assisted Evaluation</h2></header><div className="review-rubric-list">{review.feedbackSections.map((section) => <article key={`${section.category}-${section.title}`}><div><h3>{formatLabel(section.title)}</h3><p>{section.summary}</p></div><strong>{section.score} / {section.maxScore}</strong><progress value={section.score} max={section.maxScore}/>{section.suggestions.length > 0 && <ul>{section.suggestions.map((suggestion) => <li key={suggestion}>{suggestion}</li>)}</ul>}</article>)}</div></section>
        <section className="workspace-card review-comments"><h2>Teacher Comments</h2>{onSaveComment ? <><textarea rows={4} maxLength={5000} value={comment} onChange={(event) => setComment(event.target.value)} aria-label="Teacher comment"/><button className="button button-primary" disabled={saving} onClick={async () => { setSaving(true); try { const value = await onSaveComment(comment); setComment(value.teacherComment ?? ""); notify.success("Comment saved."); } catch (error) { notify.error(error, "Comment could not be saved."); } finally { setSaving(false); } }}>{saving ? "Submitting…" : "Submit Comment"}</button></> : <p>{review.teacherComment || "No teacher comment yet."}</p>}</section>
      </main>
    </section>
  </div>;
}

function ScoreRing({ score, max }: { score: number | undefined; max: number | undefined }) { const percentage = score !== undefined && max ? Math.round(score / max * 100) : 0; return <div className="review-score-ring" style={{ "--score": `${percentage * 3.6}deg` } as React.CSSProperties}><span><strong>{score ?? "—"}</strong><small>of {max ?? "—"}</small></span></div>; }

function ReviewFile({ review, file, files, fileIndex, setFileIndex, pages, pageNumber, setPageNumber, selectedIssueId, onSelectIssue }: { review: SubmissionReviewDto; file: SubmissionReviewDto["files"][number]; files: SubmissionReviewDto["files"]; fileIndex: number; setFileIndex: (value: number) => void; pages: NonNullable<SubmissionReviewDto["ocrPages"]>; pageNumber: number; setPageNumber: (value: number) => void; selectedIssueId: string | null; onSelectIssue: (id: string) => void }) { return <div className="review-file">{files.length > 1 && <div className="review-file-picker">{files.map((item, index) => <button key={item.id} className={index === fileIndex ? "active" : ""} onClick={() => { setFileIndex(index); setPageNumber(1); }}>{item.originalName}</button>)}</div>}{pages.length > 1 && <div className="review-page-picker" aria-label="OCR page">{pages.map((page) => <button key={page.pageNumber} aria-pressed={pageNumber === page.pageNumber} onClick={() => setPageNumber(page.pageNumber)}>Page {page.pageNumber}</button>)}</div>}{file.mimeType.startsWith("image/") ? <ReviewImage src={file.contentUrl} name={file.originalName} page={pages.find((page) => page.pageNumber === pageNumber)} issues={review.issues} selectedIssueId={selectedIssueId} onSelectIssue={onSelectIssue}/> : <iframe src={`${file.contentUrl}#page=${pageNumber}`} title={file.originalName}/>}<a href={file.contentUrl} target="_blank" rel="noreferrer">Open original file</a></div>; }

function ReviewImage({ src, name, page, issues, selectedIssueId, onSelectIssue }: { src: string | undefined; name: string; page: NonNullable<SubmissionReviewDto["ocrPages"]>[number] | undefined; issues: Issue[]; selectedIssueId: string | null; onSelectIssue: (id: string) => void }) { const words = useMemo(() => new Map(page?.words.map((word) => [word.id, word]) ?? []), [page]); const activePage = page; const annotated = activePage ? issues.flatMap((issue) => issue.sourceFileId === activePage.sourceFileId && issue.pageNumbers?.includes(activePage.pageNumber) ? (issue.wordIds ?? []).flatMap((id) => { const word = words.get(id); return word ? [{ issue, word }] : []; }) : []) : []; return <div className="review-image-stage"><img src={src} alt={`Submitted file ${name}`}/>{annotated.map(({ issue, word }, index) => <button key={`${issue.id}-${word.id}`} type="button" className={`review-image-annotation${selectedIssueId === issue.id ? " selected" : ""}`} style={{ left: `${word.boundingBox.x * 100}%`, top: `${word.boundingBox.y * 100}%`, width: `${word.boundingBox.width * 100}%`, height: `${word.boundingBox.height * 100}%` }} aria-label={`${issue.code}: ${issue.explanation ?? issue.label}`} aria-pressed={selectedIssueId === issue.id} title={`${issue.code} · ${issue.category}`} onClick={() => onSelectIssue(issue.id)}><span>{index === 0 || annotated[index - 1]?.issue.id !== issue.id ? issue.code : ""}</span></button>)}</div>; }

function ReviewText({ review, onSelectIssue }: { review: SubmissionReviewDto; onSelectIssue: (id: string) => void }) { const text = review.effectiveText || review.transcribedText || review.typedText; return <div className="review-text"><HighlightedText text={text} issues={review.issues} onSelectIssue={onSelectIssue}/></div>; }
function HighlightedText({ text, issues, onSelectIssue }: { text: string; issues: Issue[]; onSelectIssue: (id: string) => void }) { if (!text) return <p>No readable text was found.</p>; const ranged = issues.filter((issue) => issue.startIndex !== undefined && issue.endIndex !== undefined && issue.startIndex >= 0 && issue.endIndex > issue.startIndex && issue.endIndex <= text.length).sort((a, b) => a.startIndex! - b.startIndex!); const parts: ReactNode[] = []; let cursor = 0; for (const issue of ranged) { if (issue.startIndex! < cursor) continue; parts.push(text.slice(cursor, issue.startIndex)); parts.push(<mark key={issue.id} className="review-issue-highlight" tabIndex={0} role="button" aria-label={`${issue.originalText}: ${issue.explanation ?? issue.label}`} onMouseEnter={() => onSelectIssue(issue.id)} onClick={() => onSelectIssue(issue.id)} onKeyDown={(event) => { if (event.key === "Enter" || event.key === " ") { event.preventDefault(); onSelectIssue(issue.id); } }}>{text.slice(issue.startIndex, issue.endIndex)}</mark>); cursor = issue.endIndex!; } parts.push(text.slice(cursor)); return <p>{parts}</p>; }
function IssuePopover({ issue, onClose }: { issue: Issue; onClose: () => void }) { return <aside className="review-error-popover" role="dialog" aria-label={`Correction ${issue.code}`}><button aria-label="Close correction" onClick={onClose}><X/></button><header><code>{issue.code}</code><span>{formatLabel(issue.category)}</span></header><small>What to improve</small><p>{issue.explanation ?? issue.label}</p><div><del>{issue.originalText}</del>{issue.suggestedText && <><span>→</span><ins>{issue.suggestedText}</ins></>}</div></aside>; }
function groupIssues(issues: Issue[]) { const groups = new Map<string, Issue[]>(); for (const issue of issues) { const key = issue.category || "Other"; groups.set(key, [...(groups.get(key) ?? []), issue]); } return groups; }
export function formatReviewLabel(value: string) { return formatLabel(value); }
function formatLabel(value: string) { return value.replace(/[_-]+/g, " ").replace(/\b\w/g, (letter) => letter.toUpperCase()).replace(/\bAnd\b/g, "&"); }
